class Maker < ActiveHash::Base
  self.data = [
    { id: 1, name: nil },
    { id: 2, name: 'トヨタ' },
    { id: 3, name: '日産' },
    { id: 4, name: 'ホンダ' },
    { id: 5, name: 'マツダ' },
    { id: 6, name: 'スバル' },
    { id: 7, name: 'ダイハツ' },
    { id: 8, name: '三菱' },
    { id: 9, name: 'スズキ' },
    { id: 10, name: 'レクサス' },
    { id: 11, name: 'フォルクスワーゲン'},
    { id: 12, name: 'BMW' },
    { id: 13, name: 'メルセデス・ベンツ' },
    { id: 14, name: 'アウディ' },
    { id: 15, name: 'ボルボ' },
    { id: 16, name: 'プジョー' },
    { id: 17, name: 'ランドローバー' },
    { id: 18, name: 'ポルシェ' },
    { id: 19, name: 'ミニ' },
    { id: 20, name: 'キャデラック' },
    { id: 21, name: 'シボレー'},
    { id: 22, name: 'ハマー' },
    { id: 23, name: 'アストンマーティン' },
    { id: 24, name: 'ジャガー' },
    { id: 25, name: 'ロータス' },
    { id: 26, name: 'マクラーレン' },
    { id: 27, name: 'ルノー' },
    { id: 28, name: 'シトロエン' },
    { id: 29, name: 'DSオートモビル' },
    { id: 30, name: 'アルファロメオ' },
    { id: 31, name: 'フェラーリ'},
    { id: 32, name: 'ランボルギーニ' },
    { id: 33, name: 'マセラティ' },
    { id: 34, name: 'ロールスロイス' },
    { id: 35, name: 'ベントレー' },
    { id: 36, name: 'テスラ' },
    { id: 37, name: 'ルノー' },
    { id: 38, name: 'ジープ' },
    { id: 39, name: 'フォード' },
    { id: 40, name: 'アバルト' },
    { id: 41, name: 'パガーニ'},
    { id: 42, name: 'ヒュンダイ' },
    { id: 43, name: '起亜' },
    { id: 44, name: 'その他'}
  ]
end